[naver_news_breaking]
title = "네이버 금융 ─ 뉴스 ─ 실시간 속보"
url = "https://finance.naver.com/news/news_list.naver?mode=LSS2D&section_id=101&section_id2=258"
entrySelector = "ul.realtimeNewsList li.newsList.top dl dd.articleSubject"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"

[naver_news_main]
title = "네이버 금융 ─ 뉴스 ─ 주요뉴스"
url = "https://finance.naver.com/news/mainnews.naver"
entrySelector = "ul.realtimeNewsList li.newsList.top dl dd.articleSubject"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"

[naver_news_marketconditions]
title = "네이버 금융 ─ 뉴스 ─ 시황·전망"
url = "https://finance.naver.com/news/news_list.naver?mode=LSS3D&section_id=101&section_id2=258&section_id3=401"
entrySelector = "ul.realtimeNewsList li.newsList.top dl dd.articleSubject"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"

[naver_news_analysis]
title = "네이버 금융 ─ 뉴스 ─ 기업 종목분석"
url = "https://finance.naver.com/news/news_list.naver?mode=LSS3D&section_id=101&section_id2=258&section_id3=402"
entrySelector = "ul.realtimeNewsList li.newsList.top dl dd.articleSubject"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"

[naver_news_overseas]
title = "네이버 금융 ─ 뉴스 ─ 해외증시"
url = "https://finance.naver.com/news/news_list.naver?mode=LSS3D&section_id=101&section_id2=258&section_id3=403"
entrySelector = "ul.realtimeNewsList li.newsList.top dl dd.articleSubject"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"

[naver_news_bond]
title = "네이버 금융 ─ 뉴스 ─ 채권 선물"
url = "https://finance.naver.com/news/news_list.naver?mode=LSS3D&section_id=101&section_id2=258&section_id3=404"
entrySelector = "ul.realtimeNewsList li.newsList.top dl dd.articleSubject"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"

[naver_news_announce]
title = "네이버 금융 ─ 뉴스 ─ 공시 메모"
url = "https://finance.naver.com/news/news_list.naver?mode=LSS3D&section_id=101&section_id2=258&section_id3=406"
entrySelector = "ul.realtimeNewsList li.newsList.top dl dd.articleSubject"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"

[naver_news_exchange]
title = "네이버 금융 ─ 뉴스 ─ 환율"
url = "https://finance.naver.com/news/news_list.naver?mode=LSS3D&section_id=101&section_id2=258&section_id3=429"
entrySelector = "ul.realtimeNewsList li.newsList.top dl dd.articleSubject"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"


[naver_news_rank]
title = "네이버 금융 ─ 뉴스 ─ 많이 본 뉴스"
url = "https://finance.naver.com/news/news_list.naver?mode=RANK"
entrySelector = "ul.simpleNewsList li"
titleSelector = "a"
linkSelector = "a"
contentSelector = "span.press"
dateSelector = "span.wdate"
dateFormat = "yyyy-MM-dd hh:mm"
waitUntil = "networkidle"
