[naver_news_breaking]
title = "네이버 금융 ─ 뉴스 ─ 실시간 속보"
url = "https://finance.naver.com/news/news_list.naver?mode=LSS2D&section_id=101&section_id2=258"
entrySelector = "ul.realtimeNewsList li.newsList.top dl dd.articleSubject"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"

[naver_news_main]
title = "네이버 금융 ─ 뉴스 ─ 주요뉴스"
url = "https://finance.naver.com/news/mainnews.naver"
entrySelector = "ul.realtimeNewsList li.newsList.top dl dd.articleSubject"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"

[naver_news_marketconditions]
title = "네이버 금융 ─ 뉴스 ─ 시황·전망"
url = "https://finance.naver.com/news/news_list.naver?mode=LSS3D&section_id=101&section_id2=258&section_id3=401"
entrySelector = "ul.realtimeNewsList li.newsList.top dl dd.articleSubject"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"

[naver_news_analysis]
title = "네이버 금융 ─ 뉴스 ─ 기업 종목분석"
url = "https://finance.naver.com/news/news_list.naver?mode=LSS3D&section_id=101&section_id2=258&section_id3=402"
entrySelector = "ul.realtimeNewsList li.newsList.top dl dd.articleSubject"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"

[naver_news_overseas]
title = "네이버 금융 ─ 뉴스 ─ 해외증시"
url = "https://finance.naver.com/news/news_list.naver?mode=LSS3D&section_id=101&section_id2=258&section_id3=403"
entrySelector = "ul.realtimeNewsList li.newsList.top dl dd.articleSubject"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"

[naver_news_bond]
title = "네이버 금융 ─ 뉴스 ─ 채권 선물"
url = "https://finance.naver.com/news/news_list.naver?mode=LSS3D&section_id=101&section_id2=258&section_id3=404"
entrySelector = "ul.realtimeNewsList li.newsList.top dl dd.articleSubject"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"

[naver_news_announce]
title = "네이버 금융 ─ 뉴스 ─ 공시 메모"
url = "https://finance.naver.com/news/news_list.naver?mode=LSS3D&section_id=101&section_id2=258&section_id3=406"
entrySelector = "ul.realtimeNewsList li.newsList.top dl dd.articleSubject"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"

[naver_news_exchange]
title = "네이버 금융 ─ 뉴스 ─ 환율"
url = "https://finance.naver.com/news/news_list.naver?mode=LSS3D&section_id=101&section_id2=258&section_id3=429"
entrySelector = "ul.realtimeNewsList li.newsList.top dl dd.articleSubject"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"

[naver_news_rank]
title = "네이버 금융 ─ 뉴스 ─ 많이 본 뉴스"
url = "https://finance.naver.com/news/news_list.naver?mode=RANK"
entrySelector = "ul.simpleNewsList li"
titleSelector = "a"
linkSelector = "a"
contentSelector = "span.press"
dateSelector = "span.wdate"
dateFormat = "yyyy-MM-dd hh:mm"
waitUntil = "networkidle"

[naver_news_photo]
title = "네이버 금융 ─ 뉴스 ─ 포토뉴스"
url = "https://finance.naver.com/news/news_list.naver?mode=LSTD&section_id=101&section_id2=258&type=1"
entrySelector = "ul.newsList li.block1"
titleSelector = "dl dd.articleSubject a"
linkSelector = "dl dd.articleSubject a"
contentSelector = "span.press"
dateSelector = "span.wdate"
dateFormat = "yyyy-MM-dd hh:mm"
waitUntil = "networkidle"

[naver_news_tv]
title = "네이버 금융 ─ 뉴스 ─ TV뉴스"
url = "https://finance.naver.com/news/news_list.naver?mode=TV&section_id=tv"
entrySelector = "ul.newsList li.block1"
titleSelector = "dl dd.articleSubject a"
linkSelector = "dl dd.articleSubject a"
contentSelector = "span.press"
dateSelector = "span.wdate"
dateFormat = "yyyy-MM-dd hh:mm"
waitUntil = "networkidle"

[naver_market_notice]
title = "네이버 금융 ─ 투자정보 ─ 공시정보"
url = "https://finance.naver.com/news/market_notice.naver"
entrySelector = "table tbody tr"
titleSelector = "td.publicSubject > a"
linkSelector = "td.publicSubject > a"
contentSelector = "td.press"
dateSelector = "td.wdate"
dateFormat = "yy.MM.dd hh:mm"
waitUntil = "networkidle"

[naver_market_special]
title = "네이버 금융 ─ 투자정보 ─ 장중특징주"
url = "https://finance.naver.com/news/market_special.naver"
entrySelector = "table tbody tr"
titleSelector = "td.publicSubject > a"
linkSelector = "td.publicSubject > a"
contentSelector = "td.press"
dateSelector = "td.wdate"
dateFormat = "yy.MM.dd hh:mm"
waitUntil = "networkidle"

[naver_schedule]
title = "네이버 금융 ─ 오늘의 증시일정"
url = "https://finance.naver.com/news/news_search.naver?rcdate=&q=%BF%C0%B4%C3%C0%C7+%C1%F5%BD%C3%C0%CF%C1%A4&sm=title.basic&pd=1&stDateStart="
entrySelector = "dl.newsList dt.articleSubject"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"

[naver_research_company]
title = "네이버 금융 ─ 리서치 ─ 종목분석 리포트"
url = "https://finance.naver.com/research/company_list.naver"
entrySelector = "table.type_1 tbody tr:nth-child(n+3)"
titleSelector = "td:nth-child(2) a"
linkSelector = "td.file a"
contentSelector = "td:nth-child(1) a"
dateSelector = "td:nth-child(5)"
dateFormat = "yy.MM.dd"
waitUntil = "networkidle"

